// <auto-generated />
namespace Arma3BEClient.Libs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_custom_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_custom_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201612040948573_Added_custom_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
