// <auto-generated />
namespace Arma3BEClient.Libs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BadNicknames_ImportantWords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BadNicknames_ImportantWords));
        
        string IMigrationMetadata.Id
        {
            get { return "201706202056450_BadNicknames_ImportantWords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
