//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma3BEClient.Libs.ModelCompact
{
    //public partial class Sessions
    //{
    //    [Key]
    //    public int Id { get; set; }
        
    //    [Required]
    //    public System.Guid ServerId { get; set; }

    //    [Required]
    //    public System.Guid PlayerId { get; set; }
        
        
    //    public System.DateTime StartTime { get; set; }
    //    public Nullable<DateTime> EndTime { get; set; }

        
    //    public string IP { get; set; }
    //    public string Guid { get; set; }
    //    public string Comment { get; set; }

    //    public System.DateTime LastCheck { get; set; }
    //    public string Nickname { get; set; }
    //    public int Ping { get; set; }
    //    public int Number { get; set; }

    //    [ForeignKey("PlayerId")]
    //    public virtual Player Player { get; set; }

    //    [ForeignKey("ServerId")]
    //    public virtual ServerInfo ServerInfo { get; set; }
    //}
}
