//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Arma3BEClient.Libs.ModelCompact
{
    public partial class ChatLog
    {
        [Key]
        public int Id { get; set; }

        [Index]
        public string Text { get; set; }

        [Index]
        public System.Guid ServerId { get; set; }

        [Index]
        public System.DateTime Date { get; set; }

        [ForeignKey("ServerId")]
        public virtual ServerInfo ServerInfo { get; set; }
    }
}
